# -*- coding: utf-8 -*-
"""covid19 analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6_FoT0nF7gvaBS4L5q-ZoIhxr5Vl0kW
"""

pip install bar_chart_race

import bar_chart_race as bcr
import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

covid_data = pd.read_csv("covid_19_data.csv",index_col=False)

covid_data = covid_data.drop(columns=['SNo','Province/State','Last Update','Deaths','Recovered'])
covid_data.set_index('ObservationDate',inplace=True)
covid_data = covid_data.groupby(by=["Country/Region"])

arab_countries=['Egypt','Algeria','Sudan','Iraq','Morocco','Saudi Arabia','Yemen',\
                'Syria','Tunisia','Jordan','United Arab Emirates','Lebanon','Libya',\
                'West Bank and Gaza','Oman','Kuwait', 'Mauritania','Qatar', 'Bahrain','Djibouti','Comoros']
df_list = [] 
for country, _ in covid_data :
  if country in arab_countries:
    df = covid_data.get_group(country)
    df = df.drop(columns=['Country/Region'])
    df = df.rename(columns={'Confirmed':country})
    df_list.append(df)
arab_lege = pd.concat(df_list,axis=1)
arab_lege = arab_lege.fillna(0)
arab_lege = arab_lege.sort_index()

def summary(values, ranks):
    total_deaths = int(round(values.sum(), -2))
    s = f'Total cumulative cases - {total_deaths:,.0f}'
    return {'x': .99, 'y': .05, 's': s, 'ha': 'right', 'size': 8}

bcr.bar_chart_race(arab_lege, title='Arab Countries Covid19 confirmed cases', period_summary_func=summary)

